[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "lmi"
version = "0.1.0"
description = "Learned Metric Index (LMI)"
authors = [{ name = "Marek Ličko", email = "mareklicko448@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]