[package]
name = "rust-lmi"
version = "0.5.2"
edition = "2024"

[dependencies]
torch-sys = "0.18.1"
tch = "0.18.1"
half = "2.4.1"
hdf5 = { package = "hdf5-metno", version = "0.10.1", features = ["f16", "static"] }
kmeans = "1.1.0"
ndarray = "=0.16.1"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "chrono"] }
petal-decomposition = { version = "0.8", features = ["openblas-static"] }
rand_pcg = "0.3.1"


[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
criterion = "0.5.1"

[[bench]]
name = "dot_product"
harness = false
